---
- name: Configure My Fedora :)
  gather_facts: true
  hosts: localhost
  connection: local
  tasks:
    # only if Gnome Workstation...
    - include_role:
        name: gnome
      when: lookup('env', 'XDG_CURRENT_DESKTOP') != ''

    - include_role:
        name: tools

    - include_role:
        name: terminal
